### PR TITLE
copy edits to the odoo10 guide

### PR DESCRIPTION
**Pull request by EdwardAngert**
Hi @damasosanoja, I gave this guide a copy edit, and want to pass it back to you.

Let me know if you have any questions about the edits, particularly the part about updating through git (my line 99) - is updating a quick enough process that we should break it into its own short section? Otherwise, once this is merged, @pbzona will guide you through the rest of the way.

Thanks!
Edward

### CODE REVIEW

**Comment by damasosanoja** [comment]
Hi @EdwardAngert 
The article looks awesome! Thanks!
About the updating through git, I think it is fast enough (complete Odoo 10 repo is about 2.2Gb in size) a simple `git pull` command is all needed in my dev machine. That said, if we want to be more informative, we could add a very short section including the best practices when updating a "production" installation, which is basically a testing environment to ensure everything will work as expected after update is done.

**Comment by EdwardAngert** [comment]
Excellent
I think users of the guide would really benefit from having the steps written out for them.


Thanks, @damasosanoja!

**Comment by damasosanoja** [comment]
@EdwardAngert 
Ok will work on it right away.

**Comment by pbzona** [comment]
@damasosanoja Once this PR is ready, do you mind making it a new PR against our master? The original was mistakenly merged and reverted. Sorry for the confusion!

**Comment by damasosanoja** [comment]
@pbzona No problem on it.

**Pull request merged**
